stages:
  - test
  - beta
before_script:
  - "bundle config set --local path vendor/bundle"
  - "bundle install"
variables:
  PATH: "/Users/develop/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

ios_test:
  dependencies: []
  stage: test
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
      - fastlane/test_output
  script:
    - "bundle exec fastlane test"
  tags:
    - xcode

mac_test:
  dependencies: []
  stage: test
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
      - fastlane/test_output
  script:
    - "bundle exec fastlane mac test"
  tags:
    - xcode

ios_beta:
  dependencies: []
  stage: beta
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - "bundle exec fastlane beta"
  tags:
    - xcode
  only:
    - master
    - /^release\/(.*)$/
    - /^future\/(.*)$/

mac_beta:
  dependencies: []
  stage: beta
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - "bundle exec fastlane mac beta"
  tags:
    - xcode
