name: "Run SwiftLint"
on:
  pull_request:

jobs:
  swiftlint:
    name: "Run SwiftLint"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Run SwiftLint"
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: "--strict --quiet --reporter github-actions-logging"
        
